### ISSUE TITLE
Where is the behavior of getting an accessor or method from one origin and calling it on a cross-origin Location defined?

### ISSUE THREAD

**Issue by bzbarsky** [annevk/html-cross-origin-objects#16]
IDL leaves this up to HTML, but I'm not obviously seeing anything in HTML for that case...

The simple answer would be that cross-origin Location objects are not actually Location objects, but that's not really compatible with this spec, right?

**Comment by annevk** [comment]
The idea is for IDL to go away for Location objects so that would have to be defined here. Is there an internal method that we could override for this case or would this have to be special cased on a per-property basis?

**Comment by bzbarsky** [comment]
> The idea is for IDL to go away for Location objects

Wait, why?  For the same-origin case that involves redefining all sorts of stuff that IDL defines right now for us (like the behavior of all the argument and return value coercions, the prototype/constructor setup, etc).  Why would we want to do that?

It really seems to me like we want same-origin Location objects to be defined as normal IDL objects and cross-origin ones to be defined as a proxy for the same-origin one, but a proxy that doesn't affect the script settings stack (which is easy enough, since nothing affects the script settings stack unless something explicitly says it does).  Then instead of invoking the canonical internal methods on yourself in some cases for cross-origin objects you would just forward to the internal methods of the Location object you're proxying.  And that way you don't have to shoehorn two totally different behaviors into something conceptually claimed to be one object.

Again, all this modulo document.domain.  At this point I'm not sure I understand what behavior you're trying to produce for the document.domain cases....

> Is there an internal method that we could override for this case

There is not.  I mean, conceptually the getters/setters/methods just operate on internal slots or something.  Except that they do this "perform a security check" thing, which would just need to be defined.

Fwiw, Gecko just has IDL annotations for things that should be cross-origin settable/gettable/callable, and those setters/getters/methods skip the security check that is otherwise performed on the "this" value.

**Comment by annevk** [comment]
What would you do for the document.domain case? And for the navigate case?

I guess I'm okay with keeping IDL around. Adding `[SkipSecurityCheck]` or some such to IDL would then be needed. And IDL would have to continue to define `[Unforgeable]` for interfaces, just for `Location`.

**Comment by bzbarsky** [comment]
> What would you do for the document.domain case? 

Back at the time I was trying to figure out what behavior we even wanted for that case.  Now that I know what it is, I really have no idea how to spec it while preserving the ES MOP invariants, due to all the non-configurable stuff on `Location`.  :(  So I'm more or less at a loss as to how we can make this all work.

**Comment by bzbarsky** [comment]
So I guess one possible approach is to define same-origin Location objects to have internal method behavior that matches that of IDL objects (by reference to IDL, basically) and define the initial state of the object, with all its non-configurable properties, as matching some snippet of IDL, and define its methods' behavior by reference to IDL and so forth.

And for the cross-origin case we need to make the internal methods throw in most cases, but the cases that don't throw need to return _exactly_ the same things as the same-origin case, due to the non-configurability bits.  And then we get to figure out how to make the result actually have the behavior we want.

**Comment by annevk** [comment]
Having done some more testing, it seems Gecko does indeed sometimes return a "same-origin" and sometimes a "cross-origin" object. And then depending on the environment, a "same-origin" object might have a bunch of limitations that are similar to the "cross-origin" object. E.g., when you set `document.domain` or navigate a nested browsing context.

What I tried to model initially was just varying on the environment and always hand out the same proxy object. Doing that makes it impossible to preserve some invariants.

So the reword your suggested approach:
1. We'd define a same-origin `Location` object in IDL, similar to what we have now. We inline the security restrictions.
2. We'd define a cross-origin `Location` object proxy, that forwards to a same-origin `Location` object, with limitations similar to those already agreed upon, except perhaps where those violate the internal method invariants.
3. The cross-origin `Location` object proxy would be returned from cross-origin `Window` objects.

**Comment by bzbarsky** [comment]
How does that handle a cross-origin thing becoming same-origin via setting `document.domain`?

**Comment by annevk** [comment]
So maybe Gecko and Chrome are more magical than I thought.

```
console.log(Object.getPrototypeOf(loc)) // null
document.domain = "{{domains[]}}"
console.log(Object.getPrototypeOf(loc)) // Location
```

I'm not really sure how this behavior could ever conform. @domenic? @bterlson?

**Comment by bzbarsky** [comment]
That behavior can conform just fine as long as `loc` is not frozen or sealed, right?

**Comment by annevk** [comment]
So I think this is actually defined, no? With the exception of `href`'s setter and `replace()`, all methods have a security check. We'll inline that security check for all the members to make things more explicit.

**Comment by annevk** [comment]
(Most of the earlier discussion is a little bit confused, since I was trying to figure out how everything fit together still.)

**Comment by bzbarsky** [comment]
> With the exception of href's setter and replace(), all methods have a security check.

@annevk Are you referring to https://html.spec.whatwg.org/multipage/browsers.html#security-location or something else?

If that's the section you're referring to, it's talking about "access", which is not the same thing as "invoking the function".  What you want to do is define what the hook at http://heycam.github.io/webidl/#dfn-perform-a-security-check actually does.

**Comment by annevk** [comment]
I'm still at a loss at how things fit together. I have updated https://github.com/annevk/html-cross-origin-objects/blob/master/Location.md about a month ago to match my current understanding of things needing to be done, but that does not include this "perform a security check" which I don't think we discussed in Orlando. (I'm still looking for feedback on my updates to that document, but the time difference is not helping so I've been doing other things. I should probably have emailed.)

IDL says that all I get passed to "perform a security check" is the object where the Function is invoked upon and the global environment associated with the Function. Shouldn't I also have access to the name of the identifier to safelist some of them? (To be extra clear, I wouldn't know how to fill in the algorithm for this at this point.)

**Comment by annevk** [comment]
Discussion with @bzbarsky http://logs.glob.uno/?c=mozilla%23content&s=12+Jan+2016&e=12+Jan+2016#c350175 suggests we do indeed have three different security checks. And I was only accounting for two thus far. I am correct above that "perform a security check" needs to account for the property name. It probably also needs to account for type. Filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=29369 to address that in IDL.
