### ISSUE TITLE
Internal method invocation style

### ISSUE THREAD

**Issue by annevk** [annevk/html-cross-origin-objects#2]
See https://github.com/tc39/ecma262/issues/91. Currently I paper over it using DefaultInternalMethod which seems somewhat reasonable.

**Comment by domenic** [comment]
I like it. I'd call it "Ordinary" instead of "Default" and remove the term default from "default ordinary object _internalMethod_ internal method"

**Comment by annevk** [comment]
In that other thread it seems Allen values having both "default" and "ordinary". Happy to rename the abstract operation though.

The other thing that's still a bit outstanding is that if you do this, are the internal methods this default ordinary object internal method invokes, also of the default ordinary kind?

**Comment by annevk** [comment]
Turns out this is not a problem as far as I can tell. Leaving this as-is for now.
