### ISSUE TITLE
Inline IDLDefined

### ISSUE THREAD

**Issue by annevk** [annevk/html-cross-origin-objects#20]
In https://www.w3.org/Bugs/Public/show_bug.cgi?id=29376 we concluded that this would be better defined here as only `Location` needs it. What exactly it needs to say is still a little bit unclear as noted there, I hope @bholley or @bzbarsky can weigh in on that.

As @bzbarsky noted it would be best not to align this fully with `WindowProxy`'s handling of `[[Configurable]]` as that would less likely be web-compatible.

**Comment by bzbarsky** [comment]
I think it would be fine to just talk about properties defined by the IDL `Location` interface or its consequential interfaces, and leave it at that.  An informative note could point out that this includes `toJSON` and `valueOf` and whatnot.

**Comment by annevk** [comment]
I think that might end up being confusing. E.g., when IDL itself talks about members of of interfaces or consequential interfaces that excludes the members that will be added as part of IDL syntax, such as an iterable declaration adding "entries".

**Comment by annevk** [comment]
I think the way to define this is by simply putting all the properties that are IDL-defined in a slot after the object is allocated. That way this and #22 can be defined in one simple sweep.

**Comment by annevk** [comment]
@bzbarsky @heycam do you know which internal methods IDL needs when it initializes an object? I have DefineOwnProperty and OwnPropertyKeys (for my own purposes) thus far.

**Comment by bzbarsky** [comment]
IDL doesn't really define the object initialization explicitly, but seems like it can all be done with `DefineOwnProperty` only.
