### ISSUE TITLE
Why not incorporate the invariant violation fixes from domenic/window-proxy-spec?

### ISSUE THREAD

**Issue by domenic** [annevk/html-cross-origin-objects#30]
https://github.com/domenic/window-proxy-spec's [[DefineOwnProperty]] and [[GetOwnProperty]] contain tricksy tricks derived from much back and forth debating. They are now implemented in Firefox, for Window Proxy at least. I think this spec should incorporate them before moving on.

**Comment by annevk** [comment]
There is a note in the specification that details why that has been removed.

**Comment by domenic** [comment]
Ah, right, I forgot to follow the link.
