### ISSUE TITLE
"and @@isConcatSpreadable" should be "or @@isConcatSpreadable"

### ISSUE THREAD

**Issue by domenic** [annevk/html-cross-origin-objects#31]

**Comment by annevk** [comment]
I don't understand. When you have "one of" I would expect a list. I use this quite often too elsewhere. Cannot find a suitable reference though that discusses this.

**Comment by domenic** [comment]
One way of seeing this is to try it without the "one of", which is technically redundant (but is helpful to clarify):

If X is x, y, or z means X could be one of those things.

If X is x, y, and z means X must be all of those things at once.

The same logic holds when using "one of".

**Comment by annevk** [comment]
Is that defined somewhere, that "one of" is redundant? Happy to be wrong, but I'll need to update a bunch of specs...

**Comment by domenic** [comment]
It's not redundant in a bad way; people talk that way, and it's fine. It's just that the sentence will mean the same thing even if you remove it. ("One of" is not redundant when used in the sense "would you like to complete one of these tasks"?)

**Comment by annevk** [comment]
Right, it meaning the same thing, is that defined?

**Comment by domenic** [comment]
I can't find a reference, but can you think of any situation where they would be different?

**Comment by domenic** [comment]
Certainly they wouldn't be different in this situation.
