### ISSUE TITLE
First step of Location [[DefineOwnProperty]] seems redundant

### ISSUE THREAD

**Issue by domenic** [annevk/html-cross-origin-objects#37]
> 1. If this.[[standardDefinedProperties]] is empty, then return DefaultInternalMethod([[DefineOwnProperty]], this, P, Desc).

This will only be true during setup, I assume. In which case it will always fall through to 2.ii, right?

**Comment by annevk** [comment]
That was not clear to me. When the browser sets up the `Window` object and its `Location` object, is there a current Realm to speak of? Is it the correct one?

**Comment by domenic** [comment]
This is actually well-defined now!! :)

[create a new browsing context](https://html.spec.whatwg.org/#creating-a-new-browsing-context) step 1 calls [InitializeHostDefinedRealm](https://tc39.github.io/ecma262/#sec-initializehostdefinedrealm). Step 4 combined with step 6 make the current Realm be the newly-created Realm. Step 7 then creates the window object, calling back to "create a new browsing context" step 1's sub-bullet "For the global object, create a new `Window` object _window_."

So it should all be fine!

**Comment by annevk** [comment]
That is quite convenient.

**Comment by annevk** [comment]
This is also true for [[OwnPropertyKeys]]. Fixing that now.

**Comment by annevk** [comment]
I guess the only question is whether this is true for `Window`. Perhaps we better store the origin and effective script origin directly on the Realm?

**Comment by domenic** [comment]
Hmm I see, because IsWindowOrLocationSameOrigin relies on the current Realm having a global object, which isn't the case while Window is being created... I don't see the exact problem (who calls IsWindowOrLocationSameOrigin during this time?) but I can see the possibility.

**Comment by annevk** [comment]
Oh right, it's not a problem, since we use a window proxy object. So as long as we create that later, all should be fine.
