### ISSUE TITLE
Does IDL need [[SetPrototypeOf]] to function?

### ISSUE THREAD

**Issue by annevk** [annevk/html-cross-origin-objects#38]
@domenic @heycam is it a problem that [[SetPrototypeOf]] always returns false? Should we make it work until the platform object is created by IDL and then make it stop functioning? Or can IDL just set the [[Prototype]] internal slot and not worry about this?

It's a little unclear to me what IDL is allowed to reach and use and what is off limits, especially given it hasn't been rewritten to use all the new fancy yet.

**Comment by domenic** [comment]
I think IDL does not need it. It will call something like ES's ObjectCreate(...) which directly sets the [[Prototype]] slot.
