### ISSUE TITLE
WeakMap usage should be more vague

### ISSUE THREAD

**Issue by domenic** [annevk/html-cross-origin-objects#4]
Right now it's explicitly a WeakMap object, and you do things like wm.set(...).

Probably better not to use an actual weak map, but instead use "a weak map", and use phrases like "if this@[[crossOriginPropertyDescriptorWeakMap]] has _key_, ..."

Also you consistently are missing a bracket in `[[crossOriginPropertyDescriptorWeakMap]`

**Comment by annevk** [comment]
And where is "a weak map" defined, then? Or is _waves hands_ sufficient?

**Comment by domenic** [comment]
Yeah, it'd be hand waving toward the general concept of a weak map. Similar to how HTML already uses weak reference in all its GC sections, I believe.

**Comment by annevk** [comment]
Closing this in favor of #5 since WeakMap is all wrong anyway.
