### ISSUE TITLE
cross origin functions should not be bound

### ISSUE THREAD

**Issue by bholley** [annevk/html-cross-origin-objects#7]
> Let crossOriginFunction be a new bound function for originalDesc.[[Value]].

I'm not sure where the 'bound' came from - I don't think it's compatible with what we shipped.
We should add a testcase for this.

**Comment by bholley** [comment]
Unless I'm misinterpreting what 'bound' means here?

**Comment by domenic** [comment]
Yes, bound is not correct; we discussed this in IRC. The intent is for it to be a wrapper function, i.e. `function crossOriginFunction(...args) { return originalDesc.[[Value]](...args); }`. Just need to find the write spec word-smithing for that.

**Comment by bholley** [comment]
My point was that we need to be able to .call it on a different cross-origin or same-origin object of the same type, and have the work. The 'wrapper' pseudo-code above breaks that by ignoring |this|.

**Comment by domenic** [comment]
Sorry, you're right; the wrapper I intended was the more general form `function crossOriginFunction(...args) { return originalDesc.[[Value]].call(this, ...args); }`. @annevk explained in IRC that "bound" was just his attempt at finding a spec shortcut for "wrapper", but yeah, it is not the correct choice.
