### ISSUE TITLE
Need to spec the Xray behavior somehow

### ISSUE THREAD

**Issue by bholley** [annevk/html-cross-origin-objects#9]
Or at least mention that it relies on Unforgeability. Though I'd really rather not rely on that, since the unforgeability of Location exists for entirely separate reasons (and could theoretically be removed someday), and we still need to define the "pristine property" concept for the Window case.

**Comment by annevk** [comment]
lore.txt does not mention "Xray". And "unforgeability" goes away if we specify `Location` in the manner described in this repository since it no longer relies on IDL. I need some clarification as to what you mean.

**Comment by bholley** [comment]
I'm talking about the fact that local modifications by one origin to the object are not visible to cross-origin scripts that observe it (until they become same-origin via document.domain).

**Comment by annevk** [comment]
Oh, I guess I see what you mean.

Currently it seem we cover that mostly by overriding all internal methods and only allowing access to a limited set of properties in a very specific manner.

**Comment by bholley** [comment]
I don't follow.

The current implementation does DefaultInternalMethod([[GetOwnProperty]], this, P), and then wraps the result up. If you call GetOwnProperty on the underlying object, and that underlying object has been modified in a way such that the property has something else, there's nothing in the current prose that prevents the cross-origin observer from receiving a wrapped version of the overridden function.

**Comment by annevk** [comment]
So the way the document proposes to approach this is that we hand out different `Location` objects to each effective script origin. Presumably from some kind of map that has effective script origins as keys.

**Comment by annevk** [comment]
I believe I fixed this with https://github.com/annevk/html-cross-origin-objects/commit/b8c189c7bb44d6ead04ac329dd97ef766597d125.
